#!/usr/bin/env node

var resolvePath = require('path').resolve;
var glob = require('glob');

var cwd = process.cwd();

process.argv.slice(2).forEach(function (arg) {
    var files = glob.sync(arg);
    files.forEach(function (file) {
        require(resolvePath(cwd, file));
    });
});
